'use client';

import { useState } from 'react';
import { ArrowLeft, Clock, X, Plus, Share2, Trash2, Pill, Target } from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function PrepPage() {
  const router = useRouter();
  
  const [questions, setQuestions] = useState([
    { id: 1, text: 'Discuss recent fatigue levels', checked: false },
    { id: 2, text: 'Refill blood pressure medication', checked: true },
    { id: 3, text: 'Ask about new exercise routine', checked: false },
  ]);

  const [symptoms, setSymptoms] = useState([
    'Shortness of breath',
    'Chest tightness',
    'Dizziness'
  ]);

  const [newQuestion, setNewQuestion] = useState('');
  const [primaryGoal, setPrimaryGoal] = useState('Get clearance for new exercise program');

  const toggleQuestion = (id: number) => {
    setQuestions(questions.map(q => 
      q.id === id ? { ...q, checked: !q.checked } : q
    ));
  };

  const removeQuestion = (id: number) => {
    setQuestions(questions.filter(q => q.id !== id));
  };

  const handleAddQuestion = (e: React.FormEvent) => {
    e.preventDefault();
    if (newQuestion.trim()) {
      setQuestions([...questions, { id: Date.now(), text: newQuestion.trim(), checked: false }]);
      setNewQuestion('');
    }
  };

  const removeSymptom = (index: number) => {
    setSymptoms(symptoms.filter((_, i) => i !== index));
  };

  const addSymptom = () => {
    const text = window.prompt('Enter a new symptom:');
    if (text && text.trim()) {
      setSymptoms([...symptoms, text.trim()]);
    }
  };

  const exportReport = () => {
    const content = `VISIT PREP REPORT\n\nDate: ${new Date().toLocaleDateString()}\n\nPRIMARY GOAL:\n${primaryGoal}\n\nQUESTIONS FOR DOCTOR:\n${questions.map(q => `- [${q.checked ? 'X' : ' '}] ${q.text}`).join('\n')}\n\nSYMPTOMS TO REPORT:\n${symptoms.map(s => `- ${s}`).join('\n')}\n\nGenerated by PatientPal`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Visit_Prep_${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 flex flex-col font-display bg-slate-50 dark:bg-slate-950 min-h-screen">
      {/* Header */}
      <div className="flex items-center bg-white/80 dark:bg-slate-900/80 backdrop-blur-md p-4 sticky top-0 z-10 border-b border-slate-200 dark:border-slate-800">
        <div 
          onClick={() => router.back()}
          className="text-slate-600 dark:text-slate-300 flex size-10 shrink-0 items-center justify-center rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 cursor-pointer transition-colors"
        >
          <ArrowLeft className="w-6 h-6" />
        </div>
        <h2 className="text-slate-900 dark:text-slate-100 text-lg font-bold leading-tight flex-1 text-center pr-10">Visit Prep</h2>
      </div>

      <div className="p-4 space-y-6 pb-8">
        {/* Next Appointment Card */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-5 border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-start gap-4">
            <div className="bg-primary text-white p-3 rounded-xl flex flex-col items-center justify-center min-w-[64px] shadow-md shadow-primary/20">
              <span className="text-xs font-medium uppercase tracking-wider">Oct</span>
              <span className="text-2xl font-bold">24</span>
            </div>
            <div className="flex flex-col">
              <p className="text-slate-900 dark:text-slate-100 text-lg font-bold leading-tight">Dr. Sarah Smith</p>
              <p className="text-primary text-sm font-semibold mb-1">Cardiology</p>
              <p className="text-slate-500 dark:text-slate-400 text-sm font-medium flex items-center gap-1.5">
                <Clock className="w-4 h-4" /> 10:00 AM
              </p>
            </div>
          </div>
        </div>

        {/* Primary Goal Section */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-5 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-slate-900 dark:text-slate-100 font-bold text-lg">
            <Target className="w-5 h-5 text-orange-500" />
            <h3>Primary Goal</h3>
          </div>
          <textarea 
            value={primaryGoal}
            onChange={(e) => setPrimaryGoal(e.target.value)}
            className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-3 text-sm text-slate-700 dark:text-slate-300 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none resize-none"
            rows={2}
            placeholder="What is the main reason for your visit?"
          />
        </div>

        {/* Current Medications Summary */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-5 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-slate-900 dark:text-slate-100 font-bold text-lg">
              <Pill className="w-5 h-5 text-blue-500" />
              <h3>Current Meds</h3>
            </div>
            <button onClick={() => router.push('/medications')} className="text-primary text-sm font-semibold hover:underline">Edit</button>
          </div>
          <div className="flex flex-wrap gap-2">
            <span className="px-3 py-1.5 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400 border border-blue-100 dark:border-blue-800 rounded-lg text-sm font-medium">Lisinopril 10mg</span>
            <span className="px-3 py-1.5 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400 border border-blue-100 dark:border-blue-800 rounded-lg text-sm font-medium">Metformin 500mg</span>
            <span className="px-3 py-1.5 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400 border border-blue-100 dark:border-blue-800 rounded-lg text-sm font-medium">Atorvastatin 20mg</span>
          </div>
        </div>

        {/* Symptoms Section */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-5 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
          <h3 className="text-slate-900 dark:text-slate-100 text-lg font-bold">Symptoms to Report</h3>
          <div className="flex flex-wrap gap-2">
            {symptoms.map((symptom, index) => (
              <div key={index} className="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 border border-red-100 dark:border-red-800 rounded-full text-sm font-medium">
                <span>{symptom}</span>
                <X 
                  className="w-3.5 h-3.5 cursor-pointer hover:opacity-70" 
                  onClick={() => removeSymptom(index)}
                />
              </div>
            ))}
            <button 
              onClick={addSymptom}
              className="flex items-center gap-1 px-3 py-1.5 border border-dashed border-slate-300 dark:border-slate-600 text-slate-500 dark:text-slate-400 rounded-full text-sm font-medium hover:border-slate-400 dark:hover:border-slate-400 transition-colors"
            >
              <Plus className="w-4 h-4" /> Add Symptom
            </button>
          </div>
        </div>

        {/* Questions Section */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-5 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-slate-900 dark:text-slate-100 text-lg font-bold">Questions for Doctor</h3>
            <span className="text-xs font-bold text-primary bg-primary/10 px-2.5 py-1 rounded-full">{questions.length}</span>
          </div>
          
          <div className="space-y-2">
            {questions.length === 0 ? (
              <p className="text-sm text-slate-500 py-2 text-center">No questions added yet.</p>
            ) : (
              questions.map((q) => (
                <div key={q.id} className="flex items-start justify-between py-2 group">
                  <label className="flex items-start gap-x-3 cursor-pointer flex-1">
                    <input 
                      type="checkbox" 
                      checked={q.checked}
                      onChange={() => toggleQuestion(q.id)}
                      className="mt-1 h-5 w-5 rounded border-slate-300 dark:border-slate-600 bg-transparent text-primary focus:ring-primary focus:ring-offset-0" 
                    />
                    <span className={`text-slate-700 dark:text-slate-300 text-base leading-snug ${q.checked ? 'line-through opacity-50' : ''}`}>
                      {q.text}
                    </span>
                  </label>
                  <button 
                    onClick={() => removeQuestion(q.id)}
                    className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              ))
            )}
          </div>

          {/* Add Question Input */}
          <form onSubmit={handleAddQuestion} className="pt-2 flex gap-2">
            <input 
              type="text"
              value={newQuestion}
              onChange={(e) => setNewQuestion(e.target.value)}
              placeholder="Type a new question..."
              className="flex-1 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-2.5 text-sm text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none"
            />
            <button 
              type="submit"
              disabled={!newQuestion.trim()}
              className="bg-primary text-white p-2.5 rounded-xl disabled:opacity-50 hover:bg-primary/90 transition-colors"
            >
              <Plus className="w-5 h-5" />
            </button>
          </form>
        </div>

        {/* Export Button */}
        <button 
          onClick={exportReport}
          className="w-full flex items-center justify-center gap-2 py-3.5 bg-primary text-white font-bold rounded-xl shadow-lg shadow-primary/20 hover:bg-primary/90 transition-colors mt-6"
        >
          <Share2 className="w-5 h-5" />
          Export Report for Doctor
        </button>
      </div>
    </div>
  );
}
